"""agregando tabla horario

Revision ID: 43c165969e61
Revises: f64179e4b9cc
Create Date: 2025-05-23 03:01:49.810446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c165969e61'
down_revision = 'f64179e4b9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('curso_gestion_materia_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['curso_gestion_materia_id'], ['curso_gestion_materia.id'], ),
    sa.ForeignKeyConstraint(['dia_id'], ['dias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curso_gestion_materia', schema=None) as batch_op:
        batch_op.drop_column('horario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso_gestion_materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario', sa.VARCHAR(), autoincrement=False, nullable=False))

    op.drop_table('horarios')
    op.drop_table('dias')
    # ### end Alembic commands ###
