"""agregando tablas para el sprint 1

Revision ID: c70467db173b
Revises: f1865f4248ba
Create Date: 2025-05-18 05:55:28.775045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c70467db173b'
down_revision = 'f1865f4248ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gestiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('estado', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_gestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_aprobados', sa.Integer(), nullable=True),
    sa.Column('total_reprobados', sa.Integer(), nullable=True),
    sa.Column('total_abandono', sa.Integer(), nullable=True),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('estado', sa.String(length=3), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('gestion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['gestion_id'], ['gestiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('grado', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=3), nullable=False),
    sa.Column('gestion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gestion_id'], ['gestiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_gestion_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.String(), nullable=False),
    sa.Column('cantidad_aprobados', sa.Integer(), nullable=True),
    sa.Column('cantidad_reprobados', sa.Integer(), nullable=True),
    sa.Column('cantidad_abandono', sa.Integer(), nullable=True),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('estado', sa.String(length=3), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('curso_gestion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_gestion_id'], ['curso_gestion.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('docente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docente',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], name='docente_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='docente_pkey')
    )
    op.drop_table('curso_gestion_materia')
    op.drop_table('docentes')
    op.drop_table('periodos')
    op.drop_table('curso_gestion')
    op.drop_table('materias')
    op.drop_table('gestiones')
    op.drop_table('cursos')
    # ### end Alembic commands ###
