"""agregando campo estado a horario

Revision ID: e1fe6cb4c0e8
Revises: 43c165969e61
Create Date: 2025-05-23 03:03:11.349360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fe6cb4c0e8'
down_revision = '43c165969e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
