"""creando tabla colegio y agregando softdelete a todas las tablas

Revision ID: f64179e4b9cc
Revises: c70467db173b
Create Date: 2025-05-22 22:42:09.384084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64179e4b9cc'
down_revision = 'c70467db173b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colegio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('total_alumnos', sa.Integer(), nullable=True),
    sa.Column('gestion', sa.String(length=40), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('origen_x', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('origen_y', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('destino_x', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('destino_y', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('url_icon', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curso_gestion', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))


    with op.batch_alter_table('curso_gestion_materia', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.alter_column('docente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))


    with op.batch_alter_table('docentes', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))


    with op.batch_alter_table('gestiones', schema=None) as batch_op:
#        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))


    with op.batch_alter_table('materias', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))


    with op.batch_alter_table('periodos', schema=None) as batch_op:
#        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periodos', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('gestiones', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('curso_gestion_materia', schema=None) as batch_op:
        batch_op.alter_column('docente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('curso_gestion', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    op.drop_table('colegio')
    # ### end Alembic commands ###
